# Generated by Django 4.2.6 on 2025-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
